### ISSUE TITLE
data missing for many engines at the moment

### ISSUE THREAD

**Issue by michaelficarra** [CanadaHonk/test262.fyi#57] opened 2024-06-11 11:33 UTC
Something seems to be broken.

<img width="317" alt="image" src="https://github.com/CanadaHonk/test262.fyi/assets/218840/dfb4ec85-c1e9-4d2b-8894-48a94ce0b308">

Data is only available for these 4 engines right now.

**Comment by CanadaHonk** [comment] 2024-06-11 11:35
Duplicate of #56, should hopefully be fixed soon by CI restart

**Closed by CanadaHonk** 2024-06-11 11:35 UTC
